import 'package:drift/drift.dart';

import '../../../../database/database.dart';
import '../../domain/entities/user.dart';

/// Mapper for converting between User entity and database UserEntity
class UserMapper {
  UserMapper._();

  /// Convert database entity to domain entity
  static User fromEntity(UserEntity entity) {
    return User(
      id: entity.id,
      email: entity.email,
      displayName: entity.displayName,
      remoteId: entity.remoteId,
      age: entity.age,
      heightCm: entity.heightCm,
      weightKg: entity.weightKg,
      isAnonymous: entity.isAnonymous,
      createdAt: entity.createdAt,
      updatedAt: entity.updatedAt,
      isDirty: entity.isDirty,
      syncVersion: entity.syncVersion,
      lastSyncedAt: entity.lastSyncedAt,
    );
  }

  /// Convert domain entity to database companion for insert/update
  static UsersCompanion toCompanion(User user) {
    return UsersCompanion.insert(
      id: user.id,
      email: Value(user.email),
      displayName: Value(user.displayName),
      remoteId: Value(user.remoteId),
      age: Value(user.age),
      heightCm: Value(user.heightCm),
      weightKg: Value(user.weightKg),
      isAnonymous: Value(user.isAnonymous),
      createdAt: Value(user.createdAt),
      updatedAt: Value(user.updatedAt),
      isDirty: Value(user.isDirty),
      syncVersion: Value(user.syncVersion),
      lastSyncedAt: Value(user.lastSyncedAt),
    );
  }

  /// Convert domain entity to JSON for remote sync
  static Map<String, dynamic> toJson(User user) {
    return {
      'uid': user.remoteId ?? user.id,
      'local_id': user.id,
      'email': user.email,
      'display_name': user.displayName,
      'age': user.age,
      'height_cm': user.heightCm,
      'weight_kg': user.weightKg,
      'is_anonymous': user.isAnonymous,
      'created_at': user.createdAt.toIso8601String(),
      'updated_at': user.updatedAt.toIso8601String(),
      'sync_version': user.syncVersion,
    };
  }

  /// Convert JSON from remote to domain entity
  static User fromJson(Map<String, dynamic> json, {String? localId}) {
    return User(
      id: localId ?? json['local_id'] as String? ?? json['id'] as String,
      email: json['email'] as String?,
      displayName: json['display_name'] as String?,
      remoteId: json['uid'] as String? ?? json['id'] as String?,
      age: json['age'] as int?,
      heightCm: (json['height_cm'] as num?)?.toDouble(),
      weightKg: (json['weight_kg'] as num?)?.toDouble(),
      isAnonymous: json['is_anonymous'] as bool? ?? true,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      isDirty: false,
      syncVersion: json['sync_version'] as int? ?? 0,
      lastSyncedAt: DateTime.now(),
    );
  }
}

// Note: UserEntity.copyWith is generated by Drift with this signature:
// - email, displayName, supabaseId, lastSyncedAt: Use Value<T?>(value) or Value.absent()
// - id, isAnonymous, createdAt, updatedAt, isDirty, syncVersion: Use raw values or null to keep current
